[0m16:49:46.217597 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002E6635BF0B0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002E65FBF1C10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002E6639E0EC0>]}


============================== 16:49:46.226638 | 9daf8d47-d4ad-464a-a8a4-9d1591d4a393 ==============================
[0m16:49:46.226638 [info ] [MainThread]: Running with dbt=1.8.3
[0m16:49:46.228597 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'version_check': 'True', 'log_path': 'logs', 'fail_fast': 'False', 'profiles_dir': 'C:\\Users\\Aizaz\\.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'log_format': 'default', 'static_parser': 'True', 'introspect': 'True', 'invocation_command': 'dbt init', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m16:49:46.279232 [warn ] [MainThread]: [ConfigFolderDirectory]: Unable to parse dict {'dir': WindowsPath('C:/Users/Aizaz/.dbt')}
[0m16:49:46.280233 [info ] [MainThread]: Creating dbt configuration folder at 
[0m16:49:58.797394 [debug] [MainThread]: Starter project path: C:\Users\Aizaz\AppData\Local\Programs\Python\Python312\Lib\site-packages\dbt\include\starter_project
[0m16:49:58.845770 [info ] [MainThread]: 
Your new dbt project "custom_elt" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m16:49:58.850762 [info ] [MainThread]: Setting up your profile.
[0m16:57:47.371984 [info ] [MainThread]: Profile custom_elt written to C:\Users\Aizaz\.dbt\profiles.yml using target's profile_template.yml and your supplied values. Run 'dbt debug' to validate the connection.
[0m16:57:47.377365 [debug] [MainThread]: Command `dbt init` succeeded at 16:57:47.376764 after 481.38 seconds
[0m16:57:47.378889 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002E65FC34D70>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002E6639E0EC0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002E6635BEBA0>]}
[0m16:57:47.379889 [debug] [MainThread]: Flushing usage events
[0m16:58:12.058767 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000026E33B3D460>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000026E33B3F860>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000026E33B3E7E0>]}


============================== 16:58:12.066992 | d593b366-a01d-4570-9507-0dae97d1324c ==============================
[0m16:58:12.066992 [info ] [MainThread]: Running with dbt=1.8.3
[0m16:58:12.068955 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'fail_fast': 'False', 'log_path': 'logs', 'debug': 'False', 'profiles_dir': 'C:\\Users\\Aizaz\\.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt debug', 'static_parser': 'True', 'log_format': 'default', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m16:58:12.122737 [info ] [MainThread]: dbt version: 1.8.3
[0m16:58:12.123691 [info ] [MainThread]: python version: 3.12.3
[0m16:58:12.125692 [info ] [MainThread]: python path: C:\Users\Aizaz\AppData\Local\Programs\Python\Python312\python.exe
[0m16:58:12.126693 [info ] [MainThread]: os info: Windows-10-10.0.19045-SP0
[0m16:58:12.249796 [info ] [MainThread]: Using profiles dir at C:\Users\Aizaz\.dbt
[0m16:58:12.250757 [info ] [MainThread]: Using profiles.yml file at C:\Users\Aizaz\.dbt\profiles.yml
[0m16:58:12.251751 [info ] [MainThread]: Using dbt_project.yml file at D:\Work station\Data_Engineering\ELT\dbt_project.yml
[0m16:58:12.253754 [info ] [MainThread]: adapter type: postgres
[0m16:58:12.254797 [info ] [MainThread]: adapter version: 1.8.2
[0m16:58:12.256760 [info ] [MainThread]: Configuration:
[0m16:58:12.257755 [info ] [MainThread]:   profiles.yml file [[32mOK found and valid[0m]
[0m16:58:12.258758 [info ] [MainThread]:   dbt_project.yml file [[31mERROR not found[0m]
[0m16:58:12.260758 [info ] [MainThread]: Required dependencies:
[0m16:58:12.262760 [debug] [MainThread]: Executing "git --help"
[0m16:58:12.269756 [info ] [MainThread]:  - git [[31mERROR[0m]

[0m16:58:12.270758 [info ] [MainThread]: Connection:
[0m16:58:12.272755 [info ] [MainThread]:   host: host.docker.internal
[0m16:58:12.273759 [info ] [MainThread]:   port: 5434
[0m16:58:12.274755 [info ] [MainThread]:   user: postgres
[0m16:58:12.276754 [info ] [MainThread]:   database: destination_db
[0m16:58:12.278755 [info ] [MainThread]:   schema: public
[0m16:58:12.279759 [info ] [MainThread]:   connect_timeout: 10
[0m16:58:12.282754 [info ] [MainThread]:   role: None
[0m16:58:12.283757 [info ] [MainThread]:   search_path: None
[0m16:58:12.284758 [info ] [MainThread]:   keepalives_idle: 0
[0m16:58:12.286752 [info ] [MainThread]:   sslmode: None
[0m16:58:12.287760 [info ] [MainThread]:   sslcert: None
[0m16:58:12.289756 [info ] [MainThread]:   sslkey: None
[0m16:58:12.290758 [info ] [MainThread]:   sslrootcert: None
[0m16:58:12.292760 [info ] [MainThread]:   application_name: dbt
[0m16:58:12.294757 [info ] [MainThread]:   retries: 1
[0m16:58:12.296759 [info ] [MainThread]: Registered adapter: postgres=1.8.2
[0m16:58:12.300763 [debug] [MainThread]: Acquiring new postgres connection 'debug'
[0m16:58:15.479491 [debug] [MainThread]: Using postgres connection "debug"
[0m16:58:15.480494 [debug] [MainThread]: On debug: select 1 as id
[0m16:58:15.481446 [debug] [MainThread]: Opening a new connection, currently in state init
[0m16:58:15.562201 [debug] [MainThread]: SQL status: SELECT 1 in 0.081 seconds
[0m16:58:15.564712 [debug] [MainThread]: On debug: Close
[0m16:58:15.566531 [info ] [MainThread]:   Connection test: [[32mOK connection ok[0m]

[0m16:58:15.569079 [info ] [MainThread]: [31m2 checks failed:[0m
[0m16:58:15.571601 [info ] [MainThread]: Project loading failed for the following reason:
 project path <D:\Work station\Data_Engineering\ELT\dbt_project.yml> not found

[0m16:58:15.574701 [info ] [MainThread]: Error from git --help: Could not find command, ensure it is in the user's PATH and that the user has permissions to run it: "git"

[0m16:58:15.579030 [debug] [MainThread]: Command `dbt debug` failed at 16:58:15.578998 after 3.79 seconds
[0m16:58:15.580196 [debug] [MainThread]: Connection 'debug' was properly closed.
[0m16:58:15.581428 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000026E33817770>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000026E32BD9A30>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000026E331479B0>]}
[0m16:58:15.583191 [debug] [MainThread]: Flushing usage events
[0m17:00:28.355200 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020733CFB0B0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020736BF8D40>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020736BFAA80>]}


============================== 17:00:28.360240 | c1268849-3dbe-4280-b700-7d827ec61af3 ==============================
[0m17:00:28.360240 [info ] [MainThread]: Running with dbt=1.8.3
[0m17:00:28.362200 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'version_check': 'True', 'log_path': 'logs', 'profiles_dir': 'C:\\Users\\Aizaz\\.dbt', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'log_format': 'default', 'introspect': 'True', 'static_parser': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'target_path': 'None', 'invocation_command': 'dbt init', 'send_anonymous_usage_stats': 'True'}
[0m17:00:44.305922 [info ] [MainThread]: A project called custom_elt already exists here.
[0m17:00:44.309969 [debug] [MainThread]: Command `dbt init` succeeded at 17:00:44.309969 after 16.18 seconds
[0m17:00:44.310970 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020733CFB0B0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020737DCFAA0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002073635AD50>]}
[0m17:00:44.311974 [debug] [MainThread]: Flushing usage events
